name: flutter_camp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  provider: ^6.1.5
  go_router: ^16.0.0
  http: ^1.4.0

  cached_network_image: ^3.4.1
  easy_refresh: ^3.4.0
  lottie: ^3.3.2
  deep_pick: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
    - assets/spinner/

  fonts:
    - family: Bitcount Single
      fonts:
        - asset: assets/fonts/BitcountSingle-Thin.ttf
        - asset: assets/fonts/BitcountSingle-ExtraLight.ttf
        - asset: assets/fonts/BitcountSingle-Light.ttf
        - asset: assets/fonts/BitcountSingle-Regular.ttf
        - asset: assets/fonts/BitcountSingle-Medium.ttf
        - asset: assets/fonts/BitcountSingle-SemiBold.ttf
        - asset: assets/fonts/BitcountSingle-Bold.ttf
        - asset: assets/fonts/BitcountSingle-ExtraBold.ttf
        - asset: assets/fonts/BitcountSingle-Black.ttf
